name: CI-CD Test
on:
  push:
    branch:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Before Checkout
        run: echo "Before Checkout"

      - uses: actions/checkout@v4

      - name: Show File directory
        run: ls -a

      - name: Test the CI-CD
        run: echo "CI-CD Test"
